version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "team-risk-analysis"
resolve_s3 = true
s3_prefix = "team-risk-analysis"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = []
